import { ClerkProvider } from '@clerk/nextjs/app-beta'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/shared/Navbar'
import Sidebar from '@/components/shared/Sidebar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'talkTime',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}:{
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      
      <body className={inter.className}>
      <Navbar/>
      <main className='flex flex-row'>
        
        <section>
          <div className="w-full max-w-4xl">
            {children}
          </div>
        </section>
        <Sidebar/>
      </main>
        
      </body>
    </html>
    </ClerkProvider>
  )
}

